// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQu3Fl5qDcI4brJYVwfwxxp2QBysccmI4',
    appId: '1:508088230851:web:a581ac22db352d08585376',
    messagingSenderId: '508088230851',
    projectId: 'flutter-firebase-intro-2fd37',
    authDomain: 'flutter-firebase-intro-2fd37.firebaseapp.com',
    storageBucket: 'flutter-firebase-intro-2fd37.appspot.com',
    measurementId: 'G-4NL79CBZ57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5V5RmXbZuWKqnZAQv9RENgYtEjx4kqOc',
    appId: '1:508088230851:android:5abd3c65a4341d8d585376',
    messagingSenderId: '508088230851',
    projectId: 'flutter-firebase-intro-2fd37',
    storageBucket: 'flutter-firebase-intro-2fd37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq1cHibTGZK4XbsgsVwt5xjCHarCdjpmo',
    appId: '1:508088230851:ios:dfd3ff5e456df95d585376',
    messagingSenderId: '508088230851',
    projectId: 'flutter-firebase-intro-2fd37',
    storageBucket: 'flutter-firebase-intro-2fd37.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );
}
